stages:
  - build
  - test
  - publish
  - cleanup

variables:
  VAULT_IMAGE_VERSION: "0.1.0"

# ------------------------------------------
# Build

build_image:
  stage: build
  tags:
    - dockerbuild
  variables:
    BUILD_OPTS: "--force-rm --no-cache"
  script:
    - echo "Building article714/vault:${VAULT_IMAGE_VERSION}"
    - docker build ${BUILD_OPTS} -t article714/vault:${VAULT_IMAGE_VERSION} .

# ------------------------------------------
# Tests

test_image:
  stage: test
  tags:
    - shell
  script:
    - docker run --rm -ti --cap-add=IPC_LOCK -u vault article714/vault:${VAULT_IMAGE_VERSION} vault --version
