stages:
  - build
  - test
  - publish
  - cleanup

variables:
  VAULT_IMAGE_VERSION: "0.1.0"

# ------------------------------------------
# Build

build_image:
  stage: build
  tags:
    - dockerbuild
  variables:
    BUILD_OPTS: "--force-rm --no-cache"
  script:
    - echo "Building article714/vault:${VAULT_IMAGE_VERSION}"
    - docker build ${BUILD_OPTS} -t article714/vault:${VAULT_IMAGE_VERSION} .

# ------------------------------------------
# Tests

test_image:
  stage: test
  image:
    name: article714/vault:${VAULT_IMAGE_VERSION}
  services:
    - name: article714/vault:${VAULT_IMAGE_VERSION}
      alias: vault-srv
  tags:
    - docker
  script:
    # wait for Ldap to be fully fit
    - echo "TODO"
    - id
    - vault --version
