#!/bin/sh
exec 2>&1

# setup logs
touch /var/log/vault.log
chown vault. /var/log/vault.log

# setup dir
chown vault /container/config/vault

# Run daemon
exec chpst -u vault /usr/bin/vault server -config /container/config/vault/vault.config
